apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-cluster-role
  namespace: default

---
    
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: read-only-cluster
  namespace: dev
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: read-only-cluster-binding
subjects:
- kind: ServiceAccount
  name: sa-cluster-role
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-only-cluster