version: '3.4'
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      network: host
      args:
        - CERTBOT_EMAIL=hello@mycompany.com #replace with your own email
        - DOMAIN_LIST=mycompany.com,api.mycompany.com,www.mycompany.com #replace with your own domains
    restart: always
    volumes:
      - ./nginx/config/conf.d/prod:/etc/nginx/conf.d
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443